apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: headlamp
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  sources:
    - repoURL: https://kubernetes-sigs.github.io/headlamp/
      chart: headlamp
      targetRevision: 0.41.0
      helm:
        releaseName: headlamp
        valueFiles:
          - $values/gitops/environments/pve1-testing1/headlamp-values.yaml
    - repoURL: https://github.com/jkkicks/testing-infra.git
      targetRevision: main
      ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
